"""Baseline the pipeline, unmodified, over a fixed diverse sample.

Not a scoring script -- CVC-FP has room/wall ground truth but no room
labels, and BRIDGE has neither. This runs the current, unmodified code
over 10 real plans from two conventions the model was not trained on and
records what comes out: wall/room/opening counts, how many rooms get
labelled, and which planto3d.features categories show up. Every later
phase re-runs this and diffs the table -- a regression here means a
"general" fix only worked on Soni Residence.

    python scripts/mini_set_baseline.py --checkpoint models/unet_cubicasa.pt --output docs/mini_set_baseline.md
"""

import argparse
import logging
import sys
import tempfile
import warnings
from pathlib import Path

from planto3d.features import feature_for
from planto3d.pipeline import run
from planto3d.segment import load_segmenter

# Five from each corpus -- enough to span both conventions without the
# script taking long enough that nobody re-runs it. "First five, sorted" is
# the whole reproducibility rule: no cherry-picking a favourable sample, and
# anyone can regenerate the same list from a fresh checkout with `sorted(...)
# [:5]` on the corpus directory, without this script telling them which
# files to pick.
CVC_FP_SAMPLE = ["1.png", "2.png", "3.png", "4.png", "5.png"]
BRIDGE_SAMPLE = [
    "11001.gif", "11041.gif", "110852.gif", "111243.gif", "111662.gif",
]


def _row(name: str, source: Path, segmenter) -> dict:
    with tempfile.TemporaryDirectory() as workdir:
        try:
            result = run(source, Path(workdir), segmenter=segmenter)
        except Exception as error:
            return {"plan": name, "error": str(error)}

    rooms = [room for floor in result.floors for room in floor.plan.rooms]
    labelled = sum(1 for room in rooms if room.label)
    categories = sorted({feature_for(room) for room in rooms if feature_for(room)})
    return {
        "plan": name,
        "walls": result.wall_count,
        "rooms": result.room_count,
        "openings": result.opening_count,
        "labelled": labelled,
        "categories": ", ".join(categories) or "none",
        "scale_source": result.scale_source,
    }


def _escape_for_table(message: str) -> str:
    """Make an exception's ``str()`` safe to drop into a markdown cell.

    A raw exception message can contain a literal ``|`` (closing a table
    row early and corrupting every column after it) or newlines (breaking
    the row onto multiple lines). Both have shown up in real tracebacks, so
    this is not a hypothetical -- an un-escaped error can silently mangle
    the very table meant to record that the run failed.
    """
    return message.replace("\n", " ").replace("|", "\\|")


def main(checkpoint: Path | None, output: Path, root: Path) -> None:
    warnings.filterwarnings("ignore")
    logging.disable(logging.WARNING)
    segmenter = load_segmenter(checkpoint)

    rows = []
    for name in CVC_FP_SAMPLE:
        rows.append(_row(f"cvc_fp/{name}", root / "cvc_fp" / "ImagesGT" / name, segmenter))
    for name in BRIDGE_SAMPLE:
        rows.append(_row(f"bridge/{name}", root / "bridge" / name, segmenter))

    # This file is the branch's declared regression gate -- every later
    # phase diffs against it. If every row failed, the corpus almost
    # certainly wasn't found (wrong --root, or data/ not populated), and
    # writing a table of ERROR rows over a good baseline would be worse
    # than leaving it untouched: it would report success (exit 0) while
    # silently destroying the thing being compared against.
    if rows and all("error" in row for row in rows):
        print(
            f"every plan failed under --root {root} -- refusing to overwrite "
            f"{output}. Check the path (expects {root}/cvc_fp/ImagesGT and "
            f"{root}/bridge).",
            file=sys.stderr,
        )
        for row in rows:
            print(f"  {row['plan']}: {row['error']}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# Diverse mini-set baseline",
        "",
        "Generated by `scripts/mini_set_baseline.py`. Every later phase re-runs",
        "this and diffs against it -- a regression here means a fix that only",
        "worked on Soni Residence.",
        "",
        "| Plan | Walls | Rooms | Openings | Labelled | Categories seen | Scale source |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        if "error" in row:
            lines.append(f"| {row['plan']} | ERROR: {_escape_for_table(row['error'])} | | | | | |")
            continue
        lines.append(
            f"| {row['plan']} | {row['walls']} | {row['rooms']} | "
            f"{row['openings']} | {row['labelled']} | {row['categories']} | "
            f"{row['scale_source']} |"
        )
    output.write_text("\n".join(lines) + "\n")
    print(f"wrote {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("data"),
        help="corpus root, expects <root>/cvc_fp/ImagesGT and <root>/bridge (default: data)",
    )
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--output", type=Path, default=Path("docs/mini_set_baseline.md"))
    arguments = parser.parse_args()
    main(arguments.checkpoint, arguments.output, arguments.root)
