"""Baseline the pipeline, unmodified, over a fixed diverse sample.

Not a scoring script -- CVC-FP has room/wall ground truth but no room
labels, and BRIDGE has neither. This runs the current, unmodified code
over 10 real plans from two conventions the model was not trained on and
records what comes out: wall/room/opening counts, how many rooms get
labelled, and which planto3d.features categories show up. Every later
phase re-runs this and diffs the table -- a regression here means a
"general" fix only worked on Soni Residence.

    python scripts/mini_set_baseline.py --checkpoint models/unet_cubicasa.pt --output docs/mini_set_baseline.md
"""

import argparse
import logging
import tempfile
import warnings
from pathlib import Path

from planto3d.features import feature_for
from planto3d.pipeline import run
from planto3d.segment import load_segmenter

CVC_FP_SAMPLE = ["1.png", "2.png", "3.png", "4.png", "5.png"]
BRIDGE_SAMPLE = [
    "11001.gif", "11041.gif", "110852.gif", "111243.gif", "111662.gif",
]


def _row(name: str, source: Path, segmenter) -> dict:
    with tempfile.TemporaryDirectory() as workdir:
        try:
            result = run(source, Path(workdir), segmenter=segmenter)
        except Exception as error:
            return {"plan": name, "error": str(error)}

    rooms = [room for floor in result.floors for room in floor.plan.rooms]
    labelled = sum(1 for room in rooms if room.label)
    categories = sorted({feature_for(room) for room in rooms if feature_for(room)})
    return {
        "plan": name,
        "walls": result.wall_count,
        "rooms": result.room_count,
        "openings": result.opening_count,
        "labelled": labelled,
        "categories": ", ".join(categories) or "none",
        "scale_source": result.scale_source,
    }


def main(checkpoint: Path | None, output: Path) -> None:
    warnings.filterwarnings("ignore")
    logging.disable(logging.WARNING)
    segmenter = load_segmenter(checkpoint)

    rows = []
    for name in CVC_FP_SAMPLE:
        rows.append(_row(f"cvc_fp/{name}", Path("data/cvc_fp/ImagesGT") / name, segmenter))
    for name in BRIDGE_SAMPLE:
        rows.append(_row(f"bridge/{name}", Path("data/bridge") / name, segmenter))

    lines = [
        "# Diverse mini-set baseline",
        "",
        "Generated by `scripts/mini_set_baseline.py`. Every later phase re-runs",
        "this and diffs against it -- a regression here means a fix that only",
        "worked on Soni Residence.",
        "",
        "| Plan | Walls | Rooms | Openings | Labelled | Categories seen | Scale source |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        if "error" in row:
            lines.append(f"| {row['plan']} | ERROR: {row['error']} | | | | | |")
            continue
        lines.append(
            f"| {row['plan']} | {row['walls']} | {row['rooms']} | "
            f"{row['openings']} | {row['labelled']} | {row['categories']} | "
            f"{row['scale_source']} |"
        )
    output.write_text("\n".join(lines) + "\n")
    print(f"wrote {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--output", type=Path, default=Path("docs/mini_set_baseline.md"))
    arguments = parser.parse_args()
    main(arguments.checkpoint, arguments.output)
